[package]
name         = "hop-hash"
version      = "0.1.0"
edition      = "2024"
rust-version = "1.89.0"
description  = "A Rust hash table using 8-way hopscotch hashing with constant-time worst-case lookups, and SIMD acceleration."
readme       = "README.md"
repository   = "https://github.com/jesterhearts/hop-hash"
license      = "MIT OR Apache-2.0"
keywords     = ["hashmap", "hashset", "hashtable", "hopscotch", "no-std"]
categories   = ["algorithms", "data-structures", "no-std"]

[package.metadata.docs.rs]
features     = ["std", "density-eighty-seven-point-five", "stats", "foldhash"]
rustdoc-args = ["--generate-link-to-definition"]

[[example]]
name              = "stats_demo"
required-features = ["stats", "std"]

[[bench]]
harness = false
name    = "hashtable_comparison"

[dependencies]
cfg-if   = "1.0.3"
foldhash = { version = "0.2.0", default-features = false, optional = true }

[dev-dependencies]
clap       = { version = "4.5.48", features = ["derive"] }
criterion  = "0.8.2"
hashbrown  = "0.17.1"
rand       = { version = "0.10.2", default-features = false, features = ["sys_rng"] }
rand_distr = "0.6.0"
siphasher  = "1.0.1"

[features]
default                         = ["density-eighty-seven-point-five", "eight-way", "foldhash", "std"]
density-eighty-seven-point-five = []
density-ninety-seven            = []
density-ninety-two              = []
eight-way                       = []
foldhash                        = ["dep:foldhash"]
sixteen-way                     = []
# Enable functions that allow inspecting low-level hash table statistics.
stats                           = []
std                             = []

[profile.release-with-debug]
inherits = "release"
debug    = true
